# Dependencias APT - GET
--- 
- include: deps.yml
- name: "Restarting RethinkDB"
  service:
    name=rethinkdb
    state=restarted
- name: "Copiying Project"
  copy:
    src="platzigram-db"
    dest=/opt/
    mode=u=r,g=r
- name: "Running npm install"
  command: bash -c "npm install || npm install"
    chdir="/opt/platzigram-db"
    creates="/opt/platzigram-db/node_modules"
- name: "Setting up Database"
  command: bash -c "node setup.js"
    chdir="/opt/platzigram-db"